services:

  vault:
    image: vault:1.11.0
    restart: always
    command: [ 'vault', 'server', '-dev', '-dev-listen-address=0.0.0.0:8200']
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  db:
    build: database
    image: db
    container_name: db_sqlserver
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Orion123@

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16